dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/cloud_farming?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: root
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1200000
    maximumPoolSize: 20
    minimumIdle: 5
    connectionTestQuery: SELECT 1
    validationTimeout: 5000
    keepaliveTime: 300000
rules:
  - !SHARDING
    tables:
      t_order:
        actualDataNodes: ds_0.t_order_${0..7}
        tableStrategy:
          complex:
            shardingColumns: user_id,order_no
            shardingAlgorithmName: order_table_complex_mod
      t_order_detail_sku:
        actualDataNodes: ds_0.t_order_detail_sku_${0..7}
        tableStrategy:
          complex:
            shardingColumns: order_no
            shardingAlgorithmName: order_detail_table_complex_mod
    shardingAlgorithms:
      order_table_complex_mod:
        type: CLASS_BASED
        props:
          algorithmClassName: com.vv.cloudfarming.order.dao.algorithm.OrderTableComplexAlgorithm
          sharding-count: 8
          strategy: complex
      order_detail_table_complex_mod:
        type: CLASS_BASED
        props:
          algorithmClassName: com.vv.cloudfarming.order.dao.algorithm.OrderTableComplexAlgorithm
          sharding-count: 8
          strategy: complex
props:
  sql-show: true
